/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class muppets_ext_fob_StandAloneFOB */

#ifndef _Included_muppets_ext_fob_StandAloneFOB
#define _Included_muppets_ext_fob_StandAloneFOB
#ifdef __cplusplus
extern "C" {
#endif
#undef muppets_ext_fob_StandAloneFOB_DATA_FORMAT_NO_DATA
#define muppets_ext_fob_StandAloneFOB_DATA_FORMAT_NO_DATA 0L
#undef muppets_ext_fob_StandAloneFOB_DATA_FORMAT_POSITION
#define muppets_ext_fob_StandAloneFOB_DATA_FORMAT_POSITION 1L
#undef muppets_ext_fob_StandAloneFOB_DATA_FORMAT_ANGLES
#define muppets_ext_fob_StandAloneFOB_DATA_FORMAT_ANGLES 2L
#undef muppets_ext_fob_StandAloneFOB_DATA_FORMAT_MATRIX
#define muppets_ext_fob_StandAloneFOB_DATA_FORMAT_MATRIX 3L
#undef muppets_ext_fob_StandAloneFOB_DATA_FORMAT_POSITION_AND_ANGLES
#define muppets_ext_fob_StandAloneFOB_DATA_FORMAT_POSITION_AND_ANGLES 4L
#undef muppets_ext_fob_StandAloneFOB_DATA_FORMAT_POSITION_AND_MATRIX
#define muppets_ext_fob_StandAloneFOB_DATA_FORMAT_POSITION_AND_MATRIX 5L
#undef muppets_ext_fob_StandAloneFOB_DATA_FORMAT_QUATERNION
#define muppets_ext_fob_StandAloneFOB_DATA_FORMAT_QUATERNION 7L
#undef muppets_ext_fob_StandAloneFOB_DATA_POSITION_AND_QUATERNION
#define muppets_ext_fob_StandAloneFOB_DATA_POSITION_AND_QUATERNION 8L
#undef muppets_ext_fob_StandAloneFOB_DATA_X
#define muppets_ext_fob_StandAloneFOB_DATA_X 0L
#undef muppets_ext_fob_StandAloneFOB_DATA_Y
#define muppets_ext_fob_StandAloneFOB_DATA_Y 1L
#undef muppets_ext_fob_StandAloneFOB_DATA_Z
#define muppets_ext_fob_StandAloneFOB_DATA_Z 2L
#undef muppets_ext_fob_StandAloneFOB_DATA_AZIMUTH
#define muppets_ext_fob_StandAloneFOB_DATA_AZIMUTH 3L
#undef muppets_ext_fob_StandAloneFOB_DATA_ELEVATION
#define muppets_ext_fob_StandAloneFOB_DATA_ELEVATION 4L
#undef muppets_ext_fob_StandAloneFOB_DATA_ROLL
#define muppets_ext_fob_StandAloneFOB_DATA_ROLL 5L
#undef muppets_ext_fob_StandAloneFOB_DATA_Q0
#define muppets_ext_fob_StandAloneFOB_DATA_Q0 6L
#undef muppets_ext_fob_StandAloneFOB_DATA_Q1
#define muppets_ext_fob_StandAloneFOB_DATA_Q1 7L
#undef muppets_ext_fob_StandAloneFOB_DATA_Q2
#define muppets_ext_fob_StandAloneFOB_DATA_Q2 8L
#undef muppets_ext_fob_StandAloneFOB_DATA_Q3
#define muppets_ext_fob_StandAloneFOB_DATA_Q3 9L
#undef muppets_ext_fob_StandAloneFOB_DATA_M11
#define muppets_ext_fob_StandAloneFOB_DATA_M11 10L
#undef muppets_ext_fob_StandAloneFOB_DATA_M12
#define muppets_ext_fob_StandAloneFOB_DATA_M12 11L
#undef muppets_ext_fob_StandAloneFOB_DATA_M13
#define muppets_ext_fob_StandAloneFOB_DATA_M13 12L
#undef muppets_ext_fob_StandAloneFOB_DATA_M21
#define muppets_ext_fob_StandAloneFOB_DATA_M21 13L
#undef muppets_ext_fob_StandAloneFOB_DATA_M22
#define muppets_ext_fob_StandAloneFOB_DATA_M22 14L
#undef muppets_ext_fob_StandAloneFOB_DATA_M23
#define muppets_ext_fob_StandAloneFOB_DATA_M23 15L
#undef muppets_ext_fob_StandAloneFOB_DATA_M31
#define muppets_ext_fob_StandAloneFOB_DATA_M31 16L
#undef muppets_ext_fob_StandAloneFOB_DATA_M32
#define muppets_ext_fob_StandAloneFOB_DATA_M32 17L
#undef muppets_ext_fob_StandAloneFOB_DATA_M33
#define muppets_ext_fob_StandAloneFOB_DATA_M33 18L
#undef muppets_ext_fob_StandAloneFOB_N_DATA_VALUES
#define muppets_ext_fob_StandAloneFOB_N_DATA_VALUES 19L
#undef muppets_ext_fob_StandAloneFOB_SCALING_FACTOR
#define muppets_ext_fob_StandAloneFOB_SCALING_FACTOR 32767.0
#undef muppets_ext_fob_StandAloneFOB_DEFAULT_BAUD_RATE
#define muppets_ext_fob_StandAloneFOB_DEFAULT_BAUD_RATE 115200L
#undef muppets_ext_fob_StandAloneFOB_DEFAULT_COM_PORT
#define muppets_ext_fob_StandAloneFOB_DEFAULT_COM_PORT 1L
#undef muppets_ext_fob_StandAloneFOB_DEFAULT_READ_TIMEOUT
#define muppets_ext_fob_StandAloneFOB_DEFAULT_READ_TIMEOUT 2000L
#undef muppets_ext_fob_StandAloneFOB_DEFAULT_WRITE_TIMEOUT
#define muppets_ext_fob_StandAloneFOB_DEFAULT_WRITE_TIMEOUT 2000L
/* Inaccessible static: opened */
/* Inaccessible static: comPort */
/* Inaccessible static: baudRate */
/* Inaccessible static: readTimeout */
/* Inaccessible static: writeTimeout */
/* Inaccessible static: data */
/* Inaccessible static: pos_scale */
/*
 * Class:     muppets_ext_fob_StandAloneFOB
 * Method:    nOpen
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_muppets_ext_fob_StandAloneFOB_nOpen
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     muppets_ext_fob_StandAloneFOB
 * Method:    nClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_muppets_ext_fob_StandAloneFOB_nClose
  (JNIEnv *, jclass);

/*
 * Class:     muppets_ext_fob_StandAloneFOB
 * Method:    nRefreshData
 * Signature: ([S)D
 */
JNIEXPORT jdouble JNICALL Java_muppets_ext_fob_StandAloneFOB_nRefreshData
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     muppets_ext_fob_StandAloneFOB
 * Method:    nFrameReady
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_muppets_ext_fob_StandAloneFOB_nFrameReady
  (JNIEnv *, jclass);

/*
 * Class:     muppets_ext_fob_StandAloneFOB
 * Method:    nStartStreaming
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_muppets_ext_fob_StandAloneFOB_nStartStreaming
  (JNIEnv *, jclass);

/*
 * Class:     muppets_ext_fob_StandAloneFOB
 * Method:    nStopStreaming
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_muppets_ext_fob_StandAloneFOB_nStopStreaming
  (JNIEnv *, jclass);

/*
 * Class:     muppets_ext_fob_StandAloneFOB
 * Method:    setDataFormat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_muppets_ext_fob_StandAloneFOB_setDataFormat
  (JNIEnv *, jclass, jint);

/*
 * Class:     muppets_ext_fob_StandAloneFOB
 * Method:    getDataFormat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_muppets_ext_fob_StandAloneFOB_getDataFormat
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
